package org.example;

public enum TokenType {
    // Single-character tokens.
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,SHARP,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR,COLON,

    // One or two character tokens.
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    CONVERT,

    // Literals.
    IDENTIFIER, STRING, NUMBER, BOOLEAN, LIST, TUPLE, ANY,UNIT,FUNTYPE,

    // Keywords.
    AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
    PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,LEFT,RIGHT,
    INCLUDE,

    // List function
    GET_STRUCTURE, ADD_STRUCTURE,REMOVE_STRUCTURE,SIZE_STRUCTURE,

    EOF
}
